openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /books:
    get:
      tags:
      - book-controller
      operationId: getAllBooks
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDTOWithReservation'
    post:
      tags:
        - book-controller
      operationId: addBook
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/BookDTO'
                - $ref: '#/components/schemas/BookDTOWithReservation'
        required: true
      responses:
        "201":
          description: Created
components:
  schemas:
    BookDTO:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
    BookDTOWithReservation:
        type: object
        properties:
          title:
            type: string
          author:
            type: string
          reserved:
            type: boolean